Repository leekm0310/issue-tracker, pull requests merged in 2022-06, with the labels that each got.

#2 [feat] 로그인 기능 구현
  .gitignore
  app/.gitignore
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/it/issuetracker/data/dto/GithubTokenDto.kt
  app/src/main/java/com/example/it/issuetracker/data/dto/GithubUserInfoDto.kt
  app/src/main/java/com/example/it/issuetracker/data/network/GithubApiService.kt
  app/src/main/java/com/example/it/issuetracker/data/network/GithubNetwork.kt
  app/src/main/java/com/example/it/issuetracker/data/network/GithubService.kt
  app/src/main/java/com/example/it/issuetracker/presentation/issue/MainActivity.kt
  app/src/main/java/com/example/it/issuetracker/presentation/login/LoginActivity.kt
  app/src/main/java/com/example/it/issuetracker/presentation/login/LoginViewModel.kt
  app/src/main/res/drawable-v24/img_github_logo.png
  app/src/main/res/drawable-v24/img_google_logo.png
  app/src/main/res/drawable/shape_black_button_round50.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#4 Github OAuth 를 firebase와 연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/it/issuetracker/data/dto/GithubTokenDto.kt
  app/src/main/java/com/example/it/issuetracker/data/dto/GithubUserInfoDto.kt
  app/src/main/java/com/example/it/issuetracker/data/network/GithubApiService.kt
  app/src/main/java/com/example/it/issuetracker/data/network/GithubNetwork.kt
  app/src/main/java/com/example/it/issuetracker/data/network/GithubService.kt
  app/src/main/java/com/example/it/issuetracker/presentation/login/LoginActivity.kt
  app/src/main/java/com/example/it/issuetracker/presentation/login/LoginViewModel.kt
Labels: feature

#6 Feat: 도메인 생성
  BE/src/main/java/kr/codesquad/issuetracker/domain/Comment.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/IssueLabels.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/IssueMembers.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Member.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Milestone.java
  BE/src/main/resources/application.yml
Labels: feature, BE

#8 [BE] Feat: github 로그인 기능 구현
  BE/build.gradle
  BE/src/main/java/kr/codesquad/issuetracker/config/WebConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/LoginController.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Member.java
  BE/src/main/java/kr/codesquad/issuetracker/dto/GitHubUser.java
  BE/src/main/java/kr/codesquad/issuetracker/dto/LoginResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/dto/TokenRequest.java
  BE/src/main/java/kr/codesquad/issuetracker/dto/TokenRespond.java
  BE/src/main/java/kr/codesquad/issuetracker/jwt/Jwt.java
  BE/src/main/java/kr/codesquad/issuetracker/jwt/JwtInterceptor.java
  BE/src/main/java/kr/codesquad/issuetracker/jwt/JwtProvider.java
  BE/src/main/java/kr/codesquad/issuetracker/jwt/OAuthUtils.java
  BE/src/main/java/kr/codesquad/issuetracker/repository/MemberRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/service/GithubOAuthService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MemberService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/oauth.yml
  BE/src/main/resources/templates/index.html
Labels: feature, BE

#14 Feature/issue default edit mode
  app/src/main/java/com/example/it/issuetracker/data/datasource/IssueTrackerDataSource.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/IssueTrackerDefaultDataSource.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/LabelAddDataSource.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/LabelAddDataSourceImpl.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/LabelDataSource.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/LabelDataSourceDefaultImpl.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/LabelFakeDatabase.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/SharedPrefDataSource.kt
  app/src/main/java/com/example/it/issuetracker/data/dto/LabelDto.kt
  app/src/main/java/com/example/it/issuetracker/data/dto/LabelInfoListDto.kt
  app/src/main/java/com/example/it/issuetracker/data/repository/IssueTrackerRepositoryImpl.kt
  app/src/main/java/com/example/it/issuetracker/data/repository/LabelAddRepositoryImpl.kt
  app/src/main/java/com/example/it/issuetracker/data/repository/LabelRepositoryImpl.kt
  app/src/main/java/com/example/it/issuetracker/di/dataSourceModule.kt
  app/src/main/java/com/example/it/issuetracker/di/repositoryModule.kt
  app/src/main/java/com/example/it/issuetracker/di/sharedPreferenceModule.kt
  app/src/main/java/com/example/it/issuetracker/di/viewModelModule.kt
  app/src/main/java/com/example/it/issuetracker/domain/model/Issue.kt
  app/src/main/java/com/example/it/issuetracker/domain/model/Label.kt
  app/src/main/java/com/example/it/issuetracker/domain/model/MileStone.kt
  app/src/main/java/com/example/it/issuetracker/domain/repository/IssueTrackerRepository.kt
  app/src/main/java/com/example/it/issuetracker/domain/repository/LabelAddRepository.kt
  app/src/main/java/com/example/it/issuetracker/domain/repository/LabelRepository.kt
  app/src/main/java/com/example/it/issuetracker/presentation/IssueTrackerApplication.kt
  app/src/main/java/com/example/it/issuetracker/presentation/common/RecyclerViewBindingAdapters.kt
  app/src/main/java/com/example/it/issuetracker/presentation/common/ShapeBindingAdapters.kt
  app/src/main/java/com/example/it/issuetracker/presentation/login/LoginViewModel.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/IssueAdapter.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/IssueFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/IssueUiState.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/IssueViewModel.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/LabelAdapter.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/Mode.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/RegisterIssueFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/label/BindingAdapter.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/label/LabelAddViewModel.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/label/LabelListAdapter.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/label/LabelViewModel.kt
  app/src/main/res/drawable-v24/ic_add_white.xml
  app/src/main/res/drawable-v24/ic_exit.xml
  app/src/main/res/drawable/ic_add_blue.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/shape_button_round50.xml
  app/src/main/res/layout/fragment_issue.xml
  app/src/main/res/layout/fragment_label_add.xml
  app/src/main/res/layout/fragment_register_issue.xml
  app/src/main/res/layout/item_edit_issue.xml
  app/src/main/res/layout/item_issue.xml
  app/src/main/res/layout/item_label.xml
  app/src/main/res/layout/label_item.xml
  app/src/main/res/menu/label_default_menu.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature, refactor, android

#21 [Android] 필터링 + 이슈 삭제 및 닫기
  app/src/main/java/com/example/it/issuetracker/data/datasource/IssueTrackerDataSource.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/IssueTrackerDefaultDataSource.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/LabelDataSource.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/LabelDataSourceDefaultImpl.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/LabelFakeDatabase.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/UserSharedPrefDataSource.kt
  app/src/main/java/com/example/it/issuetracker/data/dto/IssueDto.kt
  app/src/main/java/com/example/it/issuetracker/data/dto/LabelDto.kt
  app/src/main/java/com/example/it/issuetracker/data/dto/LoginDto.kt
  app/src/main/java/com/example/it/issuetracker/data/dto/Member.kt
  app/src/main/java/com/example/it/issuetracker/data/dto/MilestoneDto.kt
  app/src/main/java/com/example/it/issuetracker/data/repository/IssueTrackerRepositoryImpl.kt
  app/src/main/java/com/example/it/issuetracker/data/repository/LabelRepositoryImpl.kt
  app/src/main/java/com/example/it/issuetracker/di/viewModelModule.kt
  app/src/main/java/com/example/it/issuetracker/domain/model/Issue.kt
  app/src/main/java/com/example/it/issuetracker/domain/model/Label.kt
  app/src/main/java/com/example/it/issuetracker/domain/model/LoginInformation.kt
  app/src/main/java/com/example/it/issuetracker/domain/model/Member.kt
  app/src/main/java/com/example/it/issuetracker/domain/model/MileStone.kt
  app/src/main/java/com/example/it/issuetracker/domain/repository/IssueTrackerRepository.kt
  app/src/main/java/com/example/it/issuetracker/domain/repository/LabelRepository.kt
  app/src/main/java/com/example/it/issuetracker/presentation/customview/CustomFilter.kt
  app/src/main/java/com/example/it/issuetracker/presentation/customview/CustomSnackBar.kt
  app/src/main/java/com/example/it/issuetracker/presentation/login/LoginActivity.kt
  app/src/main/java/com/example/it/issuetracker/presentation/login/LoginViewModel.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/CacheIssue.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/IssueAdapter.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/IssueFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/IssueViewModel.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/Mode.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/filter/FilterFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/filter/FilterViewModel.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/filter/SpinnerAdapter.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/label/LabelAddViewModel.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/label/LabelFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/label/LabelListAdapter.kt
  app/src/main/res/layout/custom_snackbar.xml
  app/src/main/res/layout/fragment_filter.xml
  app/src/main/res/layout/fragment_issue.xml
  app/src/main/res/layout/item_spinner.xml
  app/src/main/res/layout/view_filter.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
Labels: feature, android

#26 [BE] 마일스톤 조회 기능 구현
  BE/src/main/java/kr/codesquad/issuetracker/controller/MilestoneController.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Comment.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/IssueLabels.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/IssueMembers.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Member.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Milestone.java
  BE/src/main/java/kr/codesquad/issuetracker/dto/MilestoneResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/repository/MilestoneRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MilestoneService.java
  BE/src/main/resources/data.sql
Labels: feature, BE

#30 [BE] 마일스톤 삭제 기능 구현
  BE/src/main/java/kr/codesquad/issuetracker/controller/MilestoneController.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MilestoneService.java
Labels: feature, BE

#34 [BE] 레이블 조회 기능 구현
  BE/src/main/java/kr/codesquad/issuetracker/controller/LabelController.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/dto/LabelResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/repository/LabelRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LabelService.java
  BE/src/main/resources/data.sql
Labels: feature, BE

#35 [BE] 레이블 삭제 기능 구현
  BE/src/main/java/kr/codesquad/issuetracker/controller/LabelController.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LabelService.java
Labels: feature, BE

#36 [BE] 레이블 추가 기능 구현
  BE/src/main/java/kr/codesquad/issuetracker/controller/LabelController.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/dto/LabelRequest.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LabelService.java
Labels: feature, BE

#42 [BE] 이슈 목록 조회 기능 구현
  BE/build.gradle
  BE/src/main/java/kr/codesquad/issuetracker/config/JpaQueryConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Comment.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/IssueLabels.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/IssueMembers.java
  BE/src/main/java/kr/codesquad/issuetracker/dto/IssueResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/dto/LabelResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/dto/MilestoneResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/repository/CustomIssueRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/repository/CustomIssueRepositoryImpl.java
  BE/src/main/java/kr/codesquad/issuetracker/repository/IssueRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
  BE/src/main/resources/data.sql
Labels: feature, BE

#43 [BE] 2차 PR 리뷰 반영
  BE/src/main/java/kr/codesquad/issuetracker/controller/LabelController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/MilestoneController.java
  BE/src/main/java/kr/codesquad/issuetracker/dto/IssueResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MilestoneService.java
Labels: feature, BE

#44 [BE] 마일스톤 조회 기능 수정
  BE/src/main/java/kr/codesquad/issuetracker/dto/MilestoneResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MilestoneService.java
Labels: refactor, BE

#45 [Android] 레이블/마일스톤 네트워크 연결 후 추가/삭제/수정 구현
  app/src/main/java/com/example/it/issuetracker/data/datasource/IssueTrackerDefaultDataSource.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/LabelDataSource.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/LabelDataSourceDefaultImpl.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/MilestoneDataSource.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/MilestoneDataSourceDefaultImpl.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/MilestoneFakeDatabase.kt
  app/src/main/java/com/example/it/issuetracker/data/dto/AddLabelDto.kt
  app/src/main/java/com/example/it/issuetracker/data/dto/AddMilestoneDto.kt
  app/src/main/java/com/example/it/issuetracker/data/dto/MilestoneDto.kt
  app/src/main/java/com/example/it/issuetracker/data/network/IssueTrackerService.kt
  app/src/main/java/com/example/it/issuetracker/data/repository/LabelRepositoryImpl.kt
  app/src/main/java/com/example/it/issuetracker/data/repository/MilestoneRepositoryImpl.kt
  app/src/main/java/com/example/it/issuetracker/di/viewModelModule.kt
  app/src/main/java/com/example/it/issuetracker/domain/repository/LabelRepository.kt
  app/src/main/java/com/example/it/issuetracker/domain/repository/MilestoneRepository.kt
  app/src/main/java/com/example/it/issuetracker/presentation/common/Constants.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/filter/FilterViewModel.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/label/LabelFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/label/LabelListAdapter.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/label/LabelUiState.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/label/LabelViewModel.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/label/add/LabelAddFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/label/add/LabelAddViewModel.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/label/add/NewLabelUiState.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/milestone/MilestoneAdapter.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/milestone/MilestoneFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/milestone/MilestoneUiState.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/milestone/MilestoneViewModel.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/milestone/add/MilestoneAddFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/milestone/add/MilestoneAddViewModel.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/milestone/add/NewMilestoneUiState.kt
  app/src/main/res/drawable/ic_calendar_gray.xml
  app/src/main/res/drawable/ic_exit_grey.xml
  app/src/main/res/drawable/ic_info_blue.xml
  app/src/main/res/layout/fragment_label.xml
  app/src/main/res/layout/fragment_label_add.xml
  app/src/main/res/layout/fragment_milestone.xml
  app/src/main/res/layout/fragment_milestone_add.xml
  app/src/main/res/layout/milestone_item.xml
  app/src/main/res/layout/toolbar_add_layout.xml
  app/src/main/res/values/strings.xml
Labels: feature, android

#46 [Android] 마이 페이지 화면 구현
  app/src/main/java/com/example/it/issuetracker/data/dto/LoginDto.kt
  app/src/main/java/com/example/it/issuetracker/data/repository/LoginRepositoryImpl.kt
  app/src/main/java/com/example/it/issuetracker/di/viewModelModule.kt
  app/src/main/java/com/example/it/issuetracker/domain/model/LoginInformation.kt
  app/src/main/java/com/example/it/issuetracker/domain/repository/LoginRepository.kt
  app/src/main/java/com/example/it/issuetracker/presentation/common/Constants.kt
  app/src/main/java/com/example/it/issuetracker/presentation/login/LoginActivity.kt
  app/src/main/java/com/example/it/issuetracker/presentation/login/LoginOption.kt
  app/src/main/java/com/example/it/issuetracker/presentation/login/LoginViewModel.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/mypage/MyPageUiState.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/mypage/MyPageViewModel.kt
  app/src/main/res/drawable/user_image_background.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: feature, android

#49 [BE] 마일스톤 편집 기능 구현
  BE/src/main/java/kr/codesquad/issuetracker/controller/MilestoneController.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Milestone.java
  BE/src/main/java/kr/codesquad/issuetracker/dto/MilestoneRequest.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MilestoneService.java
  BE/src/main/resources/data.sql
Labels: feature, BE

#50 [BE] 레이블 편집 기능 구현
  BE/src/main/java/kr/codesquad/issuetracker/controller/LabelController.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LabelService.java
  BE/src/main/resources/data.sql
Labels: feature, BE

#53 [Android] 2주차 금요일 피드백 반영
  app/src/main/java/com/example/it/issuetracker/data/datasource/IssueTrackerDataSource.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/IssueTrackerDefaultDataSource.kt
  app/src/main/java/com/example/it/issuetracker/data/repository/IssueTrackerRepositoryImpl.kt
  app/src/main/java/com/example/it/issuetracker/domain/repository/IssueTrackerRepository.kt
  app/src/main/java/com/example/it/issuetracker/presentation/common/Constants.kt
  app/src/main/java/com/example/it/issuetracker/presentation/common/DataBindingBaseFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/detail/DetailFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/filter/FilterFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/filter/FilterType.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/filter/FilterViewModel.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/list/IssueAdapter.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/list/IssueFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/list/IssueViewModel.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/register/RegisterIssueFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/search/SearchFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/search/SearchViewModel.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/label/LabelFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/label/LabelListAdapter.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/label/add/LabelAddFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/milestone/MilestoneFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/milestone/add/MilestoneAddFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/mypage/MyPageFragment.kt
Labels: android

#56 [Android] 이슈 스와이프 및 이슈 목록 네트워크 통신
  app/src/main/java/com/example/it/issuetracker/data/datasource/IssueTrackerDataSource.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/IssueTrackerDefaultDataSource.kt
  app/src/main/java/com/example/it/issuetracker/data/datasource/remote/IssueTrackerRemoteDataSource.kt
  app/src/main/java/com/example/it/issuetracker/data/dto/IssueDto.kt
  app/src/main/java/com/example/it/issuetracker/data/dto/MilestoneDto.kt
  app/src/main/java/com/example/it/issuetracker/data/network/IssueTrackerService.kt
  app/src/main/java/com/example/it/issuetracker/data/repository/IssueTrackerRepositoryImpl.kt
  app/src/main/java/com/example/it/issuetracker/di/datasourceModule.kt
  app/src/main/java/com/example/it/issuetracker/di/repositoryModule.kt
  app/src/main/java/com/example/it/issuetracker/domain/model/Issue.kt
  app/src/main/java/com/example/it/issuetracker/domain/model/MileStone.kt
  app/src/main/java/com/example/it/issuetracker/domain/repository/IssueTrackerRepository.kt
  app/src/main/java/com/example/it/issuetracker/presentation/common/BaseSwipeHelper.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/list/IssueAdapter.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/list/IssueFragment.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/list/IssueViewModel.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/issue/list/SwipeHelper.kt
  app/src/main/java/com/example/it/issuetracker/presentation/main/milestone/MilestoneViewModel.kt
  app/src/main/res/layout/item_edit_issue.xml
  app/src/main/res/layout/item_issue.xml
Labels: feature, android
